const ActionTypes = {
	SIGN_IN_USER: 'SIGN_IN_USER',
	SIGN_UP_USER: 'SIGN_UP_USER',
	AUTH_USER: 'AUTH_USER',
	TEST_FUNCTION: 'TEST_FUNCTION',
	LOG_OUT_USER: 'LOG_OUT_USER',
	AUTH_ERROR: 'AUTH_ERROR',
	SOLVE_SUDOKU: 'SOLVE_SUDOKU',
	SET_HOME: 'SET_HOME',
	RESUME: 'RESUME'
};

export default ActionTypes;
